import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

// Shared colors
export const C = {
  primary: '#6C63FF',
  batch: '#6C63FF',
  satuan: '#FF9F43',
  success: '#4ECDC4',
  warning: '#FFE66D',
  danger: '#FF4757',
  bg: '#0F0F1A',
  surface: '#1A1A2E',
  card: '#16213E',
  border: '#2A2A40',
  text: '#FFFFFF',
  muted: '#7A7A9D',
  secondary: '#A0A0C0',
  primaryAlpha: 'rgba(108, 99, 255, 0.1)',
  successAlpha: 'rgba(78, 205, 196, 0.1)',
  dangerAlpha: 'rgba(255, 71, 87, 0.1)'
};


export const dashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  greeting: { color: C.muted, fontSize: 13, fontWeight: '600' },
  titleTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  title: { color: C.text, fontSize: 22, fontWeight: '800', flexShrink: 1 },
  editTitleChip: {
    backgroundColor: C.primary + '25',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.primary + '55',
    marginLeft: 8,
  },
  editTitleChipTxt: { color: C.primary, fontSize: 10, fontWeight: '700' },

  // Tombol Top Right Add Dashboard
  addDashboardTopBtn: {
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  addDashboardTopBtnPlus: { fontSize: 14, color: '#FFF', marginRight: 4 },
  addDashboardTopBtnTxt: { color: '#FFF', fontSize: 12, fontWeight: '800' },

  // Dashboard Switcher Tabs
  switcherContainer: {
    marginTop: 4,
    marginBottom: 8,
  },
  switcherScrollContent: {
    paddingHorizontal: 24,
    gap: 8,
    paddingVertical: 4,
  },
  dashTab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  dashTabActive: {
    backgroundColor: C.primary + '22',
    borderColor: C.primary,
    borderWidth: 1.5,
  },
  dashTabTxt: { color: C.secondary, fontSize: 12, fontWeight: '700' },
  dashTabTxtActive: { color: C.text, fontWeight: '800' },
  dashTabBadge: {
    backgroundColor: C.card,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 6,
  },
  dashTabBadgeActive: {
    backgroundColor: C.primary,
  },
  dashTabBadgeTxt: { color: C.muted, fontSize: 10, fontWeight: '700' },
  dashTabBadgeTxtActive: { color: '#FFF' },
  dashTabAdd: {
    backgroundColor: C.card,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.primary + '66',
    borderStyle: 'dashed',
  },
  dashTabAddTxt: { color: C.primary, fontSize: 12, fontWeight: '700' },

  editChip: {
    backgroundColor: C.warning + '22',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.warning + '55',
  },
  editChipTxt: { color: C.warning, fontSize: 10, fontWeight: '700' },
  editBannerBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  editBannerBtnTxt: { color: '#FFF', fontSize: 12, fontWeight: '700' },
  bepBanner: {
    marginHorizontal: 24,
    marginTop: 6,
    borderRadius: 14,
    padding: 14,
    backgroundColor: C.surface,
    borderWidth: 1.5,
    borderColor: C.border,
  },
  bepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  bepTag: { color: C.muted, fontSize: 9, fontWeight: '700', letterSpacing: 0.8 },
  bepTitle: { color: C.text, fontSize: 13, fontWeight: '800', marginTop: 1 },
  progressTrack: {
    height: 8,
    backgroundColor: C.card,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 10,
  },
  progressBar: { height: '100%', borderRadius: 4 },
  bepDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  bepDetailCol: {},
  bepDetailLbl: { color: C.muted, fontSize: 10 },
  bepDetailVal: { fontSize: 13, fontWeight: '800', marginTop: 1 },
  bepNote: {
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
  },
  bepNoteTxt: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  sectionTitle: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginHorizontal: 24,
    marginTop: 16,
    marginBottom: 8,
  },
  grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 20, gap: 8 },
  card: {
    backgroundColor: C.surface,
    borderRadius: 12,
    padding: 10,
    width: (width - 56) / 2,
    marginHorizontal: 2,
    borderWidth: 1,
    borderColor: C.border,
  },
  cardHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  cardIcon: { fontSize: 18 },
  dot: { borderRadius: 20, padding: 3 },
  dotText: { fontSize: 7 },
  cardValue: { fontSize: 14, fontWeight: '800', marginBottom: 2 },
  cardTitle: { color: C.text, fontSize: 11, fontWeight: '600' },
  cardSub: { color: C.muted, fontSize: 9, marginTop: 1 },
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: 24,
    backgroundColor: C.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
  },
  stat: { flex: 1, alignItems: 'center', paddingVertical: 10 },
  statMid: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: C.border,
  },
  statNum: { color: C.primary, fontSize: 18, fontWeight: '800' },
  statLbl: { color: C.muted, fontSize: 10, marginTop: 1 },

  completeBannerBtn: {
    backgroundColor: C.success,
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
    marginTop: 8,
  },
  completeBannerBtnTxt: { color: '#0F0F1A', fontWeight: '800', fontSize: 12 },
  historyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 24,
    marginTop: 18,
    marginBottom: 8,
  },
  historySectionTitle: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  completeHeaderBtn: {
    backgroundColor: C.success + '22',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.success + '55',
  },
  completeHeaderBtnTxt: { color: C.success, fontSize: 10, fontWeight: '700' },
  historyCard: {
    backgroundColor: C.surface,
    borderRadius: 12,
    marginHorizontal: 24,
    marginBottom: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: C.border,
  },
  historyHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  historyName: { color: C.text, fontSize: 13, fontWeight: '800' },
  historyDate: { color: C.muted, fontSize: 10, marginTop: 1 },
  historyDelBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: C.danger + '22',
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyDelTxt: { fontSize: 12 },
  historyGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: C.card,
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  historyGridCol: { flex: 1, alignItems: 'center' },
  historyGridLbl: { color: C.muted, fontSize: 9, marginBottom: 1 },
  historyGridVal: { fontSize: 11, fontWeight: '700' },
  historyBadgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  historyBadgeTxt: { fontSize: 10, fontWeight: '800' },
  historySoldTxt: { color: C.secondary, fontSize: 10, fontWeight: '600' },

  salesInputCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.surface,
    padding: 12,
    marginHorizontal: 24,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  salesInputDate: { color: C.muted, fontSize: 11, marginBottom: 4 },
  salesInputVal: { color: C.primary, fontSize: 14, fontWeight: '700' },
  salesInputEditBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  salesInputEditTxt: { fontSize: 12 },
  salesInputDelBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.danger + '22',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  salesInputDelTxt: { fontSize: 12 },


  expandToggleBtn: {
    marginTop: 10,
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  expandToggleTxt: { color: C.primary, fontSize: 12, fontWeight: '700' },
  soldItemsContainer: {
    marginTop: 10,
    backgroundColor: C.card,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  soldItemsTitle: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  soldItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: C.border + '55',
  },
  soldItemName: { color: C.text, fontSize: 13, fontWeight: '700' },
  soldItemSub: { color: C.muted, fontSize: 11, marginTop: 2 },
  soldItemSubtotal: { color: C.success, fontSize: 13, fontWeight: '800' },
  noSoldItemsTxt: {
    color: C.muted,
    fontSize: 12,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 4,
  },
  historyEmptyCard: {
    backgroundColor: C.surface,
    marginHorizontal: 24,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 12,
  },
  historyEmptyIcon: { fontSize: 40, marginBottom: 8 },
  historyEmptyTitle: { color: C.text, fontSize: 16, fontWeight: '700', marginBottom: 4 },
  historyEmptyTxt: { color: C.muted, fontSize: 12, textAlign: 'center', lineHeight: 18 },

  empty: { alignItems: 'center', paddingVertical: 60, paddingHorizontal: 40 },
  emptyIcon: { fontSize: 60, marginBottom: 16 },
  emptyTitle: { color: C.text, fontSize: 20, fontWeight: '700', marginBottom: 8 },
  emptyTxt: { color: C.muted, fontSize: 14, textAlign: 'center', lineHeight: 22 },

  // Modal Dialog Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    backgroundColor: C.surface,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: C.border,
  },
  modalHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  modalTitle: { color: C.text, fontSize: 18, fontWeight: '800' },
  modalCloseIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
  },
  modalCloseIconTxt: { color: C.muted, fontSize: 16, fontWeight: '700' },
  modalSub: { color: C.muted, fontSize: 12, lineHeight: 18, marginBottom: 16 },
  inputLabel: { color: C.secondary, fontSize: 12, fontWeight: '600', marginBottom: 6 },
  inputBox: {
    backgroundColor: C.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  inputBoxError: {
    borderColor: C.danger,
  },
  textInputModal: {
    paddingVertical: 12,
    color: C.text,
    fontSize: 15,
  },
  errorTxt: {
    color: C.danger,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 12,
  },
  currencyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  currencyPrefix: {
    color: C.primary,
    fontWeight: '800',
    fontSize: 16,
    marginRight: 6,
  },
  currencyInput: {
    flex: 1,
    paddingVertical: 12,
    color: C.text,
    fontSize: 16,
  },
  saveModalBtn: {
    backgroundColor: C.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  saveModalBtnTxt: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  deleteDashBtn: {
    backgroundColor: C.danger + '1A',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: C.danger + '55',
  },
  deleteDashBtnTxt: { color: C.danger, fontSize: 13, fontWeight: '700' },
  resetModalBtn: {
    backgroundColor: C.card,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  resetModalBtnTxt: { color: C.secondary, fontSize: 12, fontWeight: '600' },
  closeModalBtn: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  closeModalBtnTxt: { color: C.muted, fontSize: 14, fontWeight: '600' },
  modeSelectorContainer: {
    flexDirection: 'column',
    gap: 10,
    marginVertical: 10,
  },
  modeOptionCard: {
    backgroundColor: C.card,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1.5,
    borderColor: C.border,
  },
  modeOptionCardActive: {
    borderColor: C.primary,
    backgroundColor: C.primary + '1F',
  },
  modeOptionEmoji: {
    fontSize: 20,
    marginBottom: 4,
  },
  modeOptionTitle: {
    color: C.secondary,
    fontSize: 14,
    fontWeight: '700',
  },
  modeOptionTitleActive: {
    color: C.primary,
  },
  modeOptionDesc: {
    color: C.muted,
    fontSize: 12,
    marginTop: 2,
  },
});
export const productsStyles = StyleSheet.create({
  container: {flex: 1, backgroundColor: C.bg},
  headerRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 16, paddingBottom: 12},
  header: {flex: 1},
  title: {color: C.text, fontSize: 24, fontWeight: '800'},
  sub: {color: C.muted, fontSize: 13, marginTop: 2},
  selectModeBtn: {
    backgroundColor: C.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  selectModeTxt: {color: C.primary, fontSize: 13, fontWeight: '700'},
  filterTabsRow: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: C.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    padding: 4,
  },
  filterTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  filterTabActive: {
    backgroundColor: C.primary,
  },
  filterTabTxt: {
    color: C.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  filterTabTxtActive: {
    color: '#FFF',
    fontWeight: '700',
  },
  selectionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: C.surface,
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: C.border,
    gap: 8,
  },
  selBtn: {
    backgroundColor: C.card,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  selTxt: {color: C.text, fontSize: 12, fontWeight: '600'},
  deleteSelectedBtn: {
    backgroundColor: C.danger,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  deleteSelectedTxt: {color: '#FFF', fontSize: 12, fontWeight: '700'},
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.surface,
    marginHorizontal: 16,
    borderRadius: 12,
    paddingHorizontal: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  searchIcon: {fontSize: 16, marginRight: 8},
  searchInput: {flex: 1, color: C.text, height: 46, fontSize: 14},
  clearBtn: {color: C.muted, fontSize: 16, padding: 4},
  card: {
    flexDirection: 'row',
    backgroundColor: C.surface,
    borderRadius: 14,
    marginBottom: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
  },
  cardSelected: {
    borderColor: C.primary,
    backgroundColor: C.primary + '1A',
  },
  checkboxContainer: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: C.border + '55',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: C.muted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  checkboxIcon: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '800',
  },
  imgBox: {width: 90, height: 90},
  img: {width: 90, height: 90},
  imgPlaceholder: {
    width: 90,
    height: 90,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  info: {flex: 1, padding: 12},
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  name: {color: C.text, fontSize: 14, fontWeight: '700', flex: 1},
  statusTag: {
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  statusTagTxt: {fontSize: 10, fontWeight: '700'},
  tagSold: {
    backgroundColor: C.success + '22',
    borderWidth: 1,
    borderColor: C.success + '55',
  },
  tagSoldTxt: {color: C.success},
  tagLunas: {
    backgroundColor: '#FFE66D25',
    borderWidth: 1,
    borderColor: '#FFE66D88',
  },
  tagLunasTxt: {color: '#FFE66D'},
  tagUnsold: {
    backgroundColor: C.card,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: C.border,
  },
  tagUnsoldTxt: {color: C.muted, fontSize: 10, fontWeight: '600'},
  cat: {color: C.muted, fontSize: 11, marginTop: 2},
  priceRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6, gap: 8},
  sellPrice: {color: C.primary, fontSize: 14, fontWeight: '700'},
  soldRevenueTxt: {color: C.success, fontSize: 11, fontWeight: '700'},
  buyPrice: {color: C.muted, fontSize: 11},
  stockRow: {flexDirection: 'row', alignItems: 'center', marginTop: 6, gap: 8},
  stockBadge: {
    backgroundColor: C.primary + '22',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  stockTxt: {color: C.primary, fontSize: 11, fontWeight: '600'},
  profit: {fontSize: 11, fontWeight: '600'},
  empty: {alignItems: 'center', paddingVertical: 60},
  emptyIcon: {fontSize: 50, marginBottom: 12},
  emptyTxt: {color: C.muted, fontSize: 14, textAlign: 'center'},
});
export const productModalStyles = StyleSheet.create({
  overlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.75)', justifyContent: 'flex-end'},
  container: {
    backgroundColor: C.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
  },
  head: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  closeBtn: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: C.border, alignItems: 'center', justifyContent: 'center',
  },
  closeTxt: {color: C.text, fontSize: 16},
  headTitle: {color: C.text, fontSize: 18, fontWeight: '700'},
  delBtn: {
    width: 34, height: 34, borderRadius: 17,
    backgroundColor: C.danger + '33', alignItems: 'center', justifyContent: 'center',
  },
  delTxt: {fontSize: 16},
  photo: {width: '100%', height: 180, borderRadius: 14, marginBottom: 12},
  photoPlaceholder: {
    width: '100%', height: 140, borderRadius: 14,
    backgroundColor: C.card, alignItems: 'center', justifyContent: 'center', marginBottom: 12,
  },
  name: {color: C.text, fontSize: 20, fontWeight: '800', marginBottom: 8},
  badges: {flexDirection: 'row', gap: 8, marginBottom: 16},
  catBadge: {
    backgroundColor: C.primary + '33', borderRadius: 8,
    paddingHorizontal: 10, paddingVertical: 4,
  },
  catTxt: {color: C.primary, fontSize: 12, fontWeight: '600'},
  barBadge: {backgroundColor: C.border, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4},
  barTxt: {color: C.muted, fontSize: 12},
  grid: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16},
  gridItem: {
    width: '47%', backgroundColor: C.card,
    borderRadius: 10, padding: 10,
    borderWidth: 1, borderColor: C.border,
  },
  gridLabel: {color: C.muted, fontSize: 11, marginBottom: 4},
  gridVal: {color: C.text, fontSize: 14, fontWeight: '700'},
  sellBox: {
    backgroundColor: C.card, borderRadius: 14,
    padding: 14, borderWidth: 1, borderColor: C.border,
  },
  sellLabel: {color: C.text, fontSize: 13, fontWeight: '600', marginBottom: 10},
  sellRow: {flexDirection: 'row', gap: 10},
  sellInput: {
    flex: 1, backgroundColor: C.surface, borderRadius: 10,
    paddingHorizontal: 14, color: C.text, fontSize: 16,
    borderWidth: 1, borderColor: C.border, height: 46,
  },
  sellBtn: {
    backgroundColor: C.success, borderRadius: 10,
    paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', height: 46,
  },
  sellBtnTxt: {color: '#FFF', fontWeight: '700', fontSize: 14},
  bottomCloseBtn: {
    marginTop: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  bottomCloseTxt: {color: C.secondary, fontSize: 14, fontWeight: '700'},
});
export const addProductStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8 },
  title: { color: C.text, fontSize: 24, fontWeight: '800' },
  sub: { color: C.muted, fontSize: 13, marginTop: 2 },
  methodContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 12,
    marginVertical: 12,
  },
  methodCard: {
    flex: 1,
    backgroundColor: C.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1.5,
    borderColor: C.border,
    alignItems: 'center',
  },
  methodCardActive: {
    borderColor: C.primary,
    backgroundColor: C.primary + '1F',
  },
  methodEmoji: { fontSize: 26, marginBottom: 4 },
  methodTitle: { color: C.secondary, fontSize: 13, fontWeight: '700' },
  methodTitleActive: { color: C.primary },
  methodSub: { color: C.muted, fontSize: 11, marginTop: 2, textAlign: 'center' },
  photoSection: { paddingHorizontal: 20, marginBottom: 8, alignItems: 'center' },
  photoPreview: {
    width: 140, height: 140, borderRadius: 16, marginBottom: 12,
    borderWidth: 2, borderColor: C.primary,
  },
  photoPlaceholder: {
    width: 140, height: 140, borderRadius: 16,
    backgroundColor: C.surface, alignItems: 'center', justifyContent: 'center',
    marginBottom: 12, borderWidth: 2, borderColor: C.border, borderStyle: 'dashed',
  },
  photoPlaceholderTxt: { color: C.muted, fontSize: 12, marginTop: 6 },
  photoBtns: { flexDirection: 'row', gap: 12 },
  photoBtn: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: C.surface, borderRadius: 10,
    paddingHorizontal: 16, paddingVertical: 10, gap: 6,
    borderWidth: 1, borderColor: C.border,
  },
  photoBtnIcon: { fontSize: 18 },
  photoBtnTxt: { color: C.text, fontSize: 13, fontWeight: '600' },
  section: {
    paddingHorizontal: 20, paddingTop: 16, paddingBottom: 4,
    borderTopWidth: 1, borderTopColor: C.border + '44',
  },
  sectionTitle: {
    color: C.muted, fontSize: 11, fontWeight: '700',
    letterSpacing: 0.8, marginBottom: 12,
  },
  label: { color: C.secondary, fontSize: 12, fontWeight: '600', marginBottom: 6 },
  input: {
    backgroundColor: C.surface, borderRadius: 10,
    paddingHorizontal: 14, paddingVertical: 12,
    color: C.text, fontSize: 14,
    borderWidth: 1, borderColor: C.border, marginBottom: 8,
  },
  currencyBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  currencyPrefix: {
    color: C.primary,
    fontWeight: '800',
    fontSize: 14,
    marginRight: 4,
  },
  currencyInput: {
    flex: 1,
    paddingVertical: 12,
    color: C.text,
    fontSize: 14,
  },
  textarea: { height: 80, textAlignVertical: 'top' },
  row: { flexDirection: 'row' },
  barcodeRow: { flexDirection: 'row', gap: 10 },
  scanBtn: {
    backgroundColor: C.primary, borderRadius: 10,
    paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', height: 46,
  },
  scanBtnTxt: { color: '#FFF', fontWeight: '700', fontSize: 13 },
  chip: {
    backgroundColor: C.surface, borderRadius: 20,
    paddingHorizontal: 14, paddingVertical: 7,
    marginRight: 8, borderWidth: 1, borderColor: C.border, marginBottom: 4,
  },
  chipOn: { backgroundColor: C.primary + '33', borderColor: C.primary },
  chipTxt: { color: C.muted, fontSize: 12, fontWeight: '500' },
  chipTxtOn: { color: C.primary, fontWeight: '700' },
  calcBox: { borderRadius: 12, borderWidth: 1, padding: 14, marginTop: 4, marginBottom: 8, backgroundColor: C.card },
  calcTitle: { color: C.text, fontSize: 13, fontWeight: '700', marginBottom: 8 },
  calcRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  calcLabel: { color: C.muted, fontSize: 13 },
  calcVal: { fontSize: 13, fontWeight: '700' },
  modalInfo: {
    backgroundColor: C.warning + '22', borderRadius: 10,
    padding: 10, marginTop: 4,
    borderWidth: 1, borderColor: C.warning + '55',
  },
  modalInfoTxt: { color: C.warning, fontSize: 13, fontWeight: '600' },
  saveBtn: {
    backgroundColor: C.primary, marginHorizontal: 20, marginTop: 20,
    borderRadius: 14, padding: 16, alignItems: 'center',
  },
  saveBtnTxt: { color: '#FFF', fontSize: 16, fontWeight: '700' },
});
export const reportsStyles = StyleSheet.create({
  container: {flex: 1, backgroundColor: C.bg},
  header: {paddingHorizontal: 20, paddingTop: 16, paddingBottom: 8},
  title: {color: C.text, fontSize: 24, fontWeight: '800'},
  sub: {color: C.muted, fontSize: 13, marginTop: 2},
  batchTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
  },
  batchTabActive: {
    backgroundColor: C.primary + '33',
    borderColor: C.primary,
  },
  batchTabTxt: {color: C.muted, fontSize: 11, fontWeight: '600'},
  batchTabTxtActive: {color: C.primary, fontWeight: '700'},
  reportNameTag: {
    color: C.primary,
    fontSize: 11,
    fontWeight: '800',
    backgroundColor: C.primary + '22',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    marginBottom: 8,
  },
  exportBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    backgroundColor: '#1E7E5E', marginHorizontal: 20, marginTop: 12,
    borderRadius: 14, padding: 16,
    borderWidth: 1, borderColor: C.success + '55',
  },
  exportIcon: {fontSize: 28},
  exportTxt: {color: '#FFF', fontSize: 16, fontWeight: '700'},
  exportSub: {color: 'rgba(255,255,255,0.6)', fontSize: 11, marginTop: 2},
  netCard: {
    marginHorizontal: 20, marginTop: 16, borderRadius: 16, padding: 20,
    backgroundColor: C.surface, borderWidth: 1, alignItems: 'center',
  },
  netLabel: {color: C.secondary, fontSize: 13, marginBottom: 6},
  netVal: {fontSize: 34, fontWeight: '900', marginBottom: 4},
  netSub: {color: C.muted, fontSize: 12},
  card: {
    backgroundColor: C.surface, marginHorizontal: 20,
    marginTop: 16, borderRadius: 16, padding: 16,
    borderWidth: 1, borderColor: C.border,
  },
  cardTitle: {color: C.text, fontSize: 15, fontWeight: '700', marginBottom: 14},
  row: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8},
  rowLabel: {color: C.muted, fontSize: 13},
  rowVal: {color: C.text, fontSize: 14, fontWeight: '700'},
  divider: {height: 1, backgroundColor: C.border, marginVertical: 2},
  formulaBox: {
    marginTop: 14,
    backgroundColor: C.bg,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  formulaTitle: {color: C.text, fontSize: 12, fontWeight: '800', marginBottom: 8},
  formulaRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  formulaLabel: {color: C.muted, fontSize: 11, fontWeight: '600'},
  formulaCode: {color: C.secondary, fontSize: 11, fontWeight: '700'},
  formulaCalcRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.surface,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginTop: 6,
  },
  sortTabs: {flexDirection: 'row', marginBottom: 8, gap: 8},
  tab: {
    paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20,
    backgroundColor: C.card, borderWidth: 1, borderColor: C.border,
  },
  tabOn: {backgroundColor: C.primary + '33', borderColor: C.primary},
  tabTxt: {color: C.muted, fontSize: 12, fontWeight: '600'},
  tabTxtOn: {color: C.primary},
  rankRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 12, borderTopWidth: 1, borderTopColor: C.border,
  },
  rankLeft: {flex: 1},
  rankName: {color: C.text, fontSize: 13, fontWeight: '600'},
  rankSub: {color: C.muted, fontSize: 11, marginTop: 2},
  rankRight: {alignItems: 'flex-end'},
  rankPnl: {fontSize: 13, fontWeight: '700'},
  rankMargin: {color: C.muted, fontSize: 11, marginTop: 2},
  empty: {alignItems: 'center', paddingVertical: 60},
  emptyIcon: {fontSize: 56, marginBottom: 14},
  emptyTitle: {color: C.text, fontSize: 20, fontWeight: '700', marginBottom: 8},
  emptyTxt: {color: C.muted, fontSize: 13, textAlign: 'center'},

  // Modal Export Selection Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxHeight: '85%',
    backgroundColor: C.surface,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: C.border,
  },
  modalHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  modalTitle: {color: C.text, fontSize: 18, fontWeight: '800'},
  modalCloseIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
  },
  modalCloseIconTxt: {color: C.muted, fontSize: 16, fontWeight: '700'},
  modalSub: {color: C.muted, fontSize: 12, lineHeight: 18, marginBottom: 16},
  exportOptionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: C.border,
    gap: 12,
  },
  exportOptionIcon: {fontSize: 24},
  exportOptionTitle: {color: C.text, fontSize: 14, fontWeight: '700'},
  exportOptionSub: {color: C.muted, fontSize: 11, marginTop: 2},
  exportBatchSectionTitle: {
    color: C.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 8,
    marginTop: 4,
  },
  exportBatchItemBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.bg,
    borderRadius: 10,
    padding: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: C.border,
    gap: 10,
  },
  exportBatchItemIcon: {fontSize: 18},
  exportBatchItemName: {color: C.text, fontSize: 13, fontWeight: '700'},
  exportBatchItemSub: {color: C.muted, fontSize: 11, marginTop: 2},
  exportBatchItemArrow: {fontSize: 16},
  closeModalBtn: {
    marginTop: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  closeModalBtnTxt: {color: C.danger, fontSize: 14, fontWeight: '700'},
});